Task2
ClevertecFrontendLab/sprint2-Dmitrii23748 pull request #1
Opened 2023-02-06 20:08 UTC by Dmitrii23748

Task2

2023-02-06 20:12 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 10.
Количество непройденных тестов: 0.
***
**app 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dmitrii23748/1675714347/app%20320px.png)
***
**app 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dmitrii23748/1675714347/app%20768px.png)
***
**app burger-menu close 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dmitrii23748/1675714347/app%20burger-menu%20close%20320px.png)
***
**app burger-menu close 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dmitrii23748/1675714347/app%20burger-menu%20close%20768px.png)
***
**app burger-menu close click not burger-menu 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dmitrii23748/1675714347/app%20burger-menu%20close%20click%20not%20burger-menu%20320px.png)
***
**app burger-menu close click not burger-menu 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dmitrii23748/1675714347/app%20burger-menu%20close%20click%20not%20burger-menu%20768px.png)
***
**app burger-menu open 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dmitrii23748/1675714347/app%20burger-menu%20open%20320px.png)
***
**app burger-menu open 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dmitrii23748/1675714347/app%20burger-menu%20open%20768px.png)
***
**app.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dmitrii23748/1675714347/app.png)
***
**book-page comment collapse.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dmitrii23748/1675714347/book-page%20comment%20collapse.png)
***
**book-page comment expand.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dmitrii23748/1675714347/book-page%20comment%20expand.png)
***
**slider after 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dmitrii23748/1675714347/slider%20after%201440px.png)
***
**slider after 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dmitrii23748/1675714347/slider%20after%20320px.png)
***
**slider after 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dmitrii23748/1675714347/slider%20after%20768px.png)
***
**slider before 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dmitrii23748/1675714347/slider%20before%201440px.png)
***
**slider before 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dmitrii23748/1675714347/slider%20before%20320px.png)
***
**slider before 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dmitrii23748/1675714347/slider%20before%20768px.png)
***
**slider more two foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dmitrii23748/1675714347/slider%20more%20two%20foto%201440px.png)
***
**slider more two foto 320px (1).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dmitrii23748/1675714347/slider%20more%20two%20foto%20320px%20(1).png)
***
**slider more two foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dmitrii23748/1675714347/slider%20more%20two%20foto%20320px.png)
***
**slider more two foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dmitrii23748/1675714347/slider%20more%20two%20foto%20768px.png)
***
**slider not foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dmitrii23748/1675714347/slider%20not%20foto%201440px.png)
***
**slider not foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dmitrii23748/1675714347/slider%20not%20foto%20320px.png)
***
**slider not foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dmitrii23748/1675714347/slider%20not%20foto%20768px.png)
***
**slider one foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dmitrii23748/1675714347/slider%20one%20foto%201440px.png)
***
**slider one foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dmitrii23748/1675714347/slider%20one%20foto%20320px.png)
***
**slider one foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Dmitrii23748/1675714347/slider%20one%20foto%20768px.png)

2023-02-06 20:29 UTC, klichkovskiy requested changes

2023-02-06 20:29 UTC, klichkovskiy commented on src/components/name-nav-comp/name-nav-component.tsx
> +    <aside className={burger ? 'aside-block__nav' : 'aside-block__nav aside-block__nav-open'} onClick={toggleBurger}>
Отсутствует закрытие меню при клике вне его области. Доделать.

2023-02-06 20:29 UTC, klichkovskiy commented on src/components/name-nav-comp/name-nav-component.tsx
> +export const NameNavComponent: React.FC<IBurger> = ({ burger, toggleBurger, removeArrowOrange, colorArrowOrange }) => {
Область адаптивного меню выходит за область экрана при малых разрешениях. Исправить

2023-02-06 20:29 UTC, klichkovskiy commented on src/components/header-comp/header-component.tsx
> +              <button type='button' className='header__burger-img-btn' onClick={toggleBurger} data-test-id='button-burger'>
Отсутствует указатель мыши что это кнопка. исправь css

2023-02-06 20:29 UTC, klichkovskiy commented on src/components/name-nav-comp/name-nav-component.tsx
> +export const NameNavComponent: React.FC<IBurger> = ({ burger, toggleBurger, removeArrowOrange, colorArrowOrange }) => {
![image](https://user-images.githubusercontent.com/62481116/217077302-95935779-81a6-48e8-93e3-db3f237251df.png)
Так не годится. Переделать. Сделать по макету

2023-02-06 20:29 UTC, klichkovskiy commented on src/components/name-nav-comp/name-nav-component.tsx
> +export const NameNavComponent: React.FC<IBurger> = ({ burger, toggleBurger, removeArrowOrange, colorArrowOrange }) => {
На странице книги отсутствует возможность вызова адаптивного меню

2023-02-06 20:29 UTC, klichkovskiy commented on src/components/name-nav-comp/name-nav-component.tsx
> +export const NameNavComponent: React.FC<IBurger> = ({ burger, toggleBurger, removeArrowOrange, colorArrowOrange }) => {
При клике и переходе на другие страницы адаптивное меню не закрывается

2023-02-07 20:56 UTC, Dmitrii23748 commented on src/components/name-nav-comp/name-nav-component.tsx
> +    <aside className={burger ? 'aside-block__nav' : 'aside-block__nav aside-block__nav-open'} onClick={toggleBurger}>
Исправил

2023-02-08 19:04 UTC, Dmitrii23748 commented on src/components/name-nav-comp/name-nav-component.tsx
> +export const NameNavComponent: React.FC<IBurger> = ({ burger, toggleBurger, removeArrowOrange, colorArrowOrange }) => {
Исправил

2023-02-08 19:05 UTC, Dmitrii23748 commented on src/components/header-comp/header-component.tsx
> +              <button type='button' className='header__burger-img-btn' onClick={toggleBurger} data-test-id='button-burger'>
Исправил

2023-02-08 19:05 UTC, Dmitrii23748 commented on src/components/name-nav-comp/name-nav-component.tsx
> +export const NameNavComponent: React.FC<IBurger> = ({ burger, toggleBurger, removeArrowOrange, colorArrowOrange }) => {
Исправил

2023-02-08 20:17 UTC, Dmitrii23748 commented on src/components/name-nav-comp/name-nav-component.tsx
> +export const NameNavComponent: React.FC<IBurger> = ({ burger, toggleBurger, removeArrowOrange, colorArrowOrange }) => {
Исправил

2023-02-08 21:23 UTC, Dmitrii23748 commented on src/components/name-nav-comp/name-nav-component.tsx
> +export const NameNavComponent: React.FC<IBurger> = ({ burger, toggleBurger, removeArrowOrange, colorArrowOrange }) => {
Исправил

2023-02-09 19:11 UTC, klichkovskiy approved these changes
Пересмотри где у тебя вылезает адаптивное меню на странице с книгой. Исправь в 3 спринте это. В этом спринте подливать больше не нужно!

2023-02-09 19:14 UTC, merged